### ISSUE TITLE
Test.h Location

### ISSUE THREAD

**Issue by juancolarte** [jakebasile/clojure-jni-example#2]
Hello ,  Test.c includes Test.h file but it is not in the repo... would you please include it?

**Comment by juancolarte** [comment]
Makefile creates, it.. disregard previous comment..

**Comment by jakebasile** [comment]
JNI generates the header file for you. It's in the [Makefile at L31](https://github.com/jakebasile/clojure-jni-example/blob/master/Makefile#L31).
